geo_location:
    resource: "@GeoBundle/Resources/config/routing/location.yml"
    prefix:   /location

geo_homepage:
    path:     /
    defaults: { _controller: GeoBundle:Default:index }

geo_bdload:
    path:     /bdload
    defaults: { _controller:GeoBundle:Default:loadentity}