geo_location:
    resource: "@GeoBundle/Resources/config/routing/location.yml"
    prefix:   /location

#geo_homepage:
    #path:     /
    #defaults: { _controller: GeoBundle:Default:index }

homepage:
    path:     /
    defaults: { _controller: GeoBundle:Default:home }

#geo_bdload:
#    path:     /bdload
#    defaults: { _controller:GeoBundle:Default:loadentity}

geo_test:
    path:     /testmap
    defaults: { _controller: GeoBundle:Default:testmap }

geo_tour:
    resource: "@GeoBundle/Resources/config/routing/tour.yml"
    prefix:   /tour

