GeoBundle\Entity\User:
    type:  entity
    table: geolyon
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        country:
            type: string
            length: 255
        city:
            type: string
            length: 255
        language:
            type: string
            length: 255
