GeoBundle\Entity\User:
    type:  entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        country:
            type: string
            length: 255
        city:
            type: string
            length: 255
        language:
            type: string
            length: 255
        point:
            type: integer
        current1:
            type: integer
        current2:
            type: integer
        current3:
            type: integer
        current4:
            type: integer
        current5:
            type: integer
        current6:
            type: integer