GeoBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: GeoBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: '80'
        firstName:
            type: string
            length: '100'
            column: first_name
        lastName:
            type: string
            length: '100'
            column: last_name
        nickName:
            type: string
            length: '100'
            column: nick_name
        password:
            type: string
            length: '100'
        role:
            type: string
            length: '100'
        salt:
            type: string
            length: '100'
        country:
            type: string
            length: '100'
        town:
            type: string
            length: '100'
        language:
            type: string
            length: '50'
        gamePoint:
            type: integer
            nullable: true
            column: game_point
    lifecycleCallbacks: {  }
