<?php

namespace GeoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends EntityRepository
{
    function uniqueRand($n, $min = 0, $max = null)
    {
        if($max === null)
            $max = getrandmax();
        $array = range($min, $max);
        $return = array();
        $keys = array_rand($array, $n);
        foreach($keys as $key)
            $return[] = $array[$key];
        return $return;
    }
}
